/* ===========================================================
   Loops — case cards data + renderer.
   GENERATED by scripts/build-cases.py from cases/cases.json — do not edit by hand.
   =========================================================== */
(function () {
  var ICON = {
    box:
      "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path pathLength=\"1\" d=\"M3 7.5 12 3l9 4.5-9 4.5z\"/><path pathLength=\"1\" d=\"M3 7.5V16l9 4.5 9-4.5V7.5\"/><path pathLength=\"1\" d=\"M12 12v8.5\"/></svg>",
    car:
      "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path pathLength=\"1\" d=\"M3.5 13l2-5.5h13l2 5.5\"/><path pathLength=\"1\" d=\"M3 13h18v4.5H3z\"/><path pathLength=\"1\" d=\"M6.5 17.5v1.5M17.5 17.5v1.5\"/></svg>",
    heart:
      "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path pathLength=\"1\" d=\"M12 20S4.5 15.5 4.5 10.2A3.7 3.7 0 0 1 12 7.3a3.7 3.7 0 0 1 7.5 2.9C19.5 15.5 12 20 12 20Z\"/></svg>",
    factory:
      "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path pathLength=\"1\" d=\"M3 21V10l5.5 3.5V10l5.5 3.5V6.5L20.5 9.5V21z\"/><path pathLength=\"1\" d=\"M3 21h18\"/></svg>",
    truck:
      "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path pathLength=\"1\" d=\"M2.5 6.5h11.5v9.5H2.5z\"/><path pathLength=\"1\" d=\"M14 9.5h4l3.5 3.5V16H14z\"/><path pathLength=\"1\" d=\"M6.5 16.5v1.5M17 16.5v1.5\"/></svg>"
  };

  window.LOOPS_CASES = [
    {
      id: "ilvi",
      img: "ilvi-premium-2026.jpg",
      client: "ILVI",
      cat: "Обувь · B2B",
      niche: ICON.factory,
      metric: "$120 тыс.",
      unit: "выручки · округлённо",
      tags: ["$5 тыс. на рекламу · округлённо", "6 стран продвижения"],
      note: "Реклама и B2B-скоринг для оптовых покупателей. Финансовые показатели округлены."
    },
    {
      id: "biorise",
      img: "biorise-clinic-2026.jpg",
      client: "BioRise",
      cat: "Клиника",
      niche: ICON.heart,
      metric: "≈950 млн",
      unit: "сум выручки Instagram-сегмента",
      tags: ["≈73% с повторными визитами", "Финансовые показатели округлены"],
      note: "От первого интереса — к завершённым и повторным визитам в клинику."
    },
    {
      id: "viamed",
      img: "viamed-cover-2026.jpg",
      client: "ViaMed",
      cat: "Клиника",
      niche: ICON.heart,
      metric: "150",
      unit: "пациентов за месяц при бюджете $500",
      tags: ["$3.3 за пациента"],
      note: "Воронка: <b>1000+ заявок → 320 лидов → 150 пациентов.</b>"
    },
    {
      id: "tak",
      img: "tak-cover-2026.jpg",
      client: "TAK Fulfillment",
      cat: "E-comm логистика",
      niche: ICON.box,
      metric: "2 831",
      unit: "диалога в месяц с потенциальными клиентами",
      tags: ["500 квал. лидов", "$4.8 за лид", "75% конверсия"],
      note: "Поток заявок вырос в&nbsp;<b>3 раза</b> — без новых сотрудников."
    },
    {
      id: "bts",
      img: "bts-cover-2026.jpg",
      client: "BTS Group",
      cat: "B2B · оборудование",
      niche: ICON.factory,
      metric: "58",
      unit: "B2B-лидов в первый месяц",
      tags: ["$7 за лид", "cold start"],
      note: "С нуля подписчиков — до оптовых продаж."
    },
    {
      id: "nwl",
      img: "nwl-warehouse-2026.png",
      client: "NWL",
      cat: "3PL-логистика",
      niche: ICON.truck,
      metric: "88",
      unit: "целевых B2B-лидов; около $21 рекламных расходов на лид",
      tags: ["70% в квалификацию"],
      note: "Воронка: <b>652 диалога → 126 контактов → 88 целевых лидов.</b>"
    },
    {
      id: "chery",
      img: "chery-main.png",
      client: "Chery",
      cat: "Автобизнес",
      niche: ICON.car,
      metric: "$15 → $4.5",
      unit: "цена лида — в 3 раза дешевле",
      tags: ["450+ заявок в месяц"],
      note: ""
    },
    {
      id: "basalt",
      img: "basalt-cover-2026.jpg",
      client: "Basalt",
      cat: "Производство · B2B",
      niche: ICON.factory,
      metric: "3 млрд сум",
      unit: "сделка, пришедшая через LinkedIn",
      tags: ["4+ встречи в месяц", "2500+ карточек на маркетплейсах"],
      note: ""
    },
    {
      id: "dco",
      img: "dco-cover-2026.jpg",
      client: "DCO Euroluxe",
      cat: "Сантехника · B2B",
      niche: ICON.box,
      metric: "45,9 млн",
      unit: "сум выручки при бюджете $200",
      tags: ["обучение сотрудника с нуля"],
      note: ""
    },
    {
      id: "feedup",
      img: "feedup-cover-2026.jpg",
      client: "FeedUp",
      cat: "HoReCa · фастфуд",
      niche: ICON.box,
      metric: "100%",
      unit: "жалоб закрыто, реакция за 10 минут",
      tags: ["ORM-система"],
      note: ""
    },
    {
      id: "izzy",
      img: "izzy-cover-2026.jpg",
      client: "IZZY",
      cat: "Кикшеринг",
      niche: ICON.car,
      metric: "+97%",
      unit: "рост базы пользователей",
      tags: ["100 000+ новых юзеров", "+20% время аренды"],
      note: ""
    },
    {
      id: "printuz",
      img: "printuz-cover-20260921.webp",
      client: "Print.uz",
      cat: "Полиграфия для бизнеса · B2B",
      niche: ICON.factory,
      metric: "265",
      unit: "лидов за месяц",
      tags: ["$2,23 — рекламы на один лид"],
      note: "Блокноты, календари, рекламная продукция: превратили конкретные задачи компаний в отдельные рекламные предложения. В кампаниях на заявки — 265 лидов по $2,23."
    },
    {
      id: "centrismedia",
      img: "centrismedia-cover-20260921.png",
      client: "Centris Media",
      cat: "Наружная реклама · B2B",
      niche: ICON.factory,
      metric: "361",
      unit: "лид за месяц",
      tags: ["$1,58 — рекламы на один лид"],
      note: "Для Centris Media запустили рекламу с заявкой как основным действием. В выбранном месяце получили 361 лид на услуги наружной рекламы."
    },
    {
      id: "printexpress",
      img: "printexpress-cover-20260921.webp",
      client: "Print Uz Express",
      cat: "Оперативная полиграфия · B2B",
      niche: ICON.factory,
      metric: "261",
      unit: "начатый диалог за месяц",
      tags: ["$2,14 — рекламы на один диалог"],
      note: "Гравировка, POS-материалы и оперативная печать: показали услуги в рекламных роликах и привели заинтересованных людей в переписку."
    },
    {
      id: "dental",
      img: "dental-case-2026.jpeg",
      client: "Dental’s Kingdom",
      cat: "Стоматология",
      niche: ICON.heart,
      metric: "117",
      unit: "диалогов за неделю",
      tags: ["$1,25 — рекламы на один диалог"],
      note: "За выбранную неделю получили 117 диалогов по $1,25. Разбираем рекламу стоматологии через конкретные запросы пациентов: детский приём, знакомство с клиникой и восстановление отсутствующего зуба."
    },
    {
      id: "centrisfit",
      img: "centrisfit-cover-20260921.jpg",
      client: "Centris Fit",
      cat: "Фитнес-клуб",
      niche: ICON.heart,
      metric: "58",
      unit: "заявок за шесть дней",
      tags: ["$2,30 — рекламы на одну заявку"],
      note: "Для Centris Fit запустили отдельную кампанию с формой заявки. За первые шесть дней в выбранном периоде она принесла 58 лидов по $2,30."
    },
    {
      id: "centrisladies",
      img: "centrisladies-cover-20260921.jpg",
      client: "Centris Ladies",
      cat: "Женский фитнес-клуб",
      niche: ICON.heart,
      metric: "53",
      unit: "диалога в кампании на сообщения",
      tags: ["$1,45 — рекламы на один диалог"],
      note: "Для Centris Ladies соединили рекламу тренировок с отдельным сценарием обращения в сообщения. Кампания на диалоги дала 53 результата по $1,45."
    },
    {
      id: "gastromarket",
      img: "gastromarket-cover-20260921.webp",
      client: "Gastromarket",
      cat: "Поставки продуктов для бизнеса",
      niche: ICON.factory,
      metric: "28",
      unit: "лидов за месяц",
      tags: ["$3,34 — рекламы на один лид"],
      note: "Для Gastromarket использовали два рекламных сценария: знакомство с предложением и сбор заявок. Кампании на лиды дали 28 обращений по $3,34."
    },
    {
      id: "dolcetta",
      img: "dolcetta-cover-20260921.webp",
      client: "Dolcetta",
      cat: "Кафе, десерты и джелато",
      niche: ICON.box,
      metric: "17,5 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,097 — за 1 000 показов"],
      note: "Dolcetta — кафе с десертами и джелато в Ташкенте. В выбранном месяце рекламные кампании дали 17,5 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    },
    {
      id: "bscafe",
      img: "bscafe-case-2026.webp",
      client: "BS Cafe",
      cat: "Кафе-ресторан",
      niche: ICON.box,
      metric: "2,1 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,092 — за 1 000 показов"],
      note: "BS Cafe — кафе-ресторан в Ташкенте. В выбранном месяце рекламные кампании дали 2,1 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    },
    {
      id: "restokids",
      img: "restokids-cover-20260921.png",
      client: "Resto Kids",
      cat: "Семейный ресторан",
      niche: ICON.box,
      metric: "2,5 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,088 — за 1 000 показов"],
      note: "Resto Kids — семейный ресторан. В выбранном месяце рекламные кампании дали 2,5 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    },
    {
      id: "centrisprint",
      img: "centrisprint-cover-20260921.webp",
      client: "Centris Print",
      cat: "Упаковка и полиграфия",
      niche: ICON.factory,
      metric: "3,8 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,090 — за 1 000 показов"],
      note: "Centris Print работает с упаковкой и полиграфией. В выбранном месяце рекламные кампании дали 3,8 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    },
    {
      id: "centriscup",
      img: "centriscup-cover-20260921.png",
      client: "Centris Print Cup",
      cat: "Бумажные стаканы для бизнеса",
      niche: ICON.factory,
      metric: "1,8 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,086 — за 1 000 показов"],
      note: "Centris Print Cup — направление бумажных стаканов для бизнеса. В выбранном месяце рекламные кампании дали 1,8 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    },
    {
      id: "blackstar",
      img: "blackstar-cover-20260921.webp",
      client: "Black Star Car Wash",
      cat: "Автомойка",
      niche: ICON.car,
      metric: "3,4 млн",
      unit: "рекламных показов за месяц",
      tags: ["$0,092 — за 1 000 показов"],
      note: "Black Star Car Wash — автомойка в Ташкенте. В выбранном месяце рекламные кампании дали 3,4 млн показов. Разбираем продвижение через продуктовые сюжеты и регулярное присутствие в ленте."
    }
  ];

  var ARROW =
    '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">' +
    '<path d="M5 12h14M13 6l6 6-6 6" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round"/></svg>';

  window.caseCardHTML = function (c, opts) {
    opts = opts || {};
    var href = (opts.href || "/cases/case-{id}/").replace("{id}", c.id);
    var goLabel = opts.goLabel || "Смотреть кейс";
    var tags = (c.tags || [])
      .map(function (t) { return '<span class="case-tag">' + t + "</span>"; })
      .join("");
    var note = c.note ? '<p class="case-note">' + c.note + "</p>" : "";
    return (
      '<div class="card hoverable case-card reveal" id="case-' + c.id + '">' +
        '<div class="case-photo">' +
          '<img class="case-img" src="/images/' + c.img + '" alt="' + c.client + '" loading="lazy" />' +
          '<span class="case-niche">' + (c.niche || "") + c.cat + "</span>" +
        "</div>" +
        '<div class="case-body">' +
          '<span class="case-client">' + c.client + "</span>" +
          '<div class="case-metric"><span class="case-num">' + c.metric +
            '<span class="unit">' + c.unit + "</span></span></div>" +
          '<div class="case-tags">' + tags + "</div>" +
          note +
          '<a class="case-go" href="' + href + '">' + goLabel + ARROW + "</a>" +
        "</div>" +
      "</div>"
    );
  };

  window.renderCases = function (container, opts) {
    if (!container) return;
    opts = opts || {};
    var list = window.LOOPS_CASES;
    if (opts.limit) list = list.slice(0, opts.limit);
    container.innerHTML = list
      .map(function (c) { return window.caseCardHTML(c, opts); })
      .join("");
  };
})();
