import React, {useEffect, useRef, useState} from 'react';
import {ArrowUpRight, ArrowRight, ArrowDown, ArrowLeft, X, List, Plus, Minus, Check, PaperPlaneTilt} from '@phosphor-icons/react';
import {cases, sectors, filters} from './data';

const scrollBehavior=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';
const TG='https://t.me/dani_gzv';
const A=import.meta.env.BASE_URL+'assets/';
function Button({children, href, className='', ...props}) { const Tag=href?'a':'button'; return <Tag href={href} className={`button ${className}`} {...props}><span>{children}</span><ArrowUpRight size={19}/></Tag> }
function Note({children,className=''}) {return <div className={`hand-note ${className}`}>{children}</div>}
function Reveal({children,className='',...props}) {const ref=useRef(); useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return; const el=ref.current; el.classList.add('will-reveal'); const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.08});o.observe(el);return()=>o.disconnect()},[]); return <div ref={ref} className={className} {...props}>{children}</div>}
function Modal({data,onClose}) {const close=useRef();useEffect(()=>{const old=document.activeElement;const orig=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=e=>{if(e.key==='Escape')onClose(); if(e.key==='Tab'){const all=[...document.querySelectorAll('.case-modal button,.case-modal a')]; const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=orig;document.removeEventListener('keydown',key);old?.focus()}},[onClose]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><section className="case-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button ref={close} className="icon-button modal-close" onClick={onClose} aria-label="Закрыть кейс"><X size={25}/></button><div className="modal-image" style={{backgroundColor:data.color}}><img src={A+data.image} alt={data.name}/><div className="modal-image-copy"><span>{data.category}</span><h2 id="modal-title">{data.name}</h2></div></div><div className="modal-content"><div className="eyebrow">КЕЙС LOOPS / {data.tools}</div><div className="modal-metrics"><div><strong>{data.result}</strong><span>{data.unit}</span></div><div><strong>{data.extra}</strong><span>{data.extraLabel}</span></div></div><h3>Задача и подход</h3><p>{data.description}</p><h3>Что получилось</h3><p>{data.detail}</p><Button href={`https://loops.uz/cases/case-${data.id}/`} target="_blank" rel="noreferrer">Полный кейс</Button><a href="#contact" onClick={onClose} className="text-link">Обсудить похожую задачу <ArrowRight size={18}/></a></div></section></div>}

export function App(){
 const[menu,setMenu]=useState(false),[filter,setFilter]=useState('Все'),[modal,setModal]=useState(null),[expanded,setExpanded]=useState(null),[faq,setFaq]=useState(null),[brief,setBrief]=useState(null),[draft,setDraft]=useState({});
 const rail=useRef(),articleRail=useRef(),hero=useRef();
 const [caseArrows,setCaseArrows]=useState({prev:false,next:true}),[articleArrows,setArticleArrows]=useState({prev:false,next:false});
 useEffect(()=>{const observe=(el,set)=>{const update=()=>set({prev:el.scrollLeft>2,next:el.scrollLeft+el.clientWidth<el.scrollWidth-2});el.addEventListener('scroll',update,{passive:true});const ro=new ResizeObserver(update);ro.observe(el);for(const child of el.children)ro.observe(child);update();return()=>{el.removeEventListener('scroll',update);ro.disconnect()}};const offCases=observe(rail.current,setCaseArrows),offArticles=observe(articleRail.current,setArticleArrows);return()=>{offCases();offArticles()}},[filter]);
 const filtered=filter==='Все'?cases:cases.filter(x=>x.filter===filter);
 useEffect(()=>{const h=hero.current;const handler=e=>{if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){h.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*16}px`);h.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*12}px`)}};h.addEventListener('pointermove',handler);return()=>h.removeEventListener('pointermove',handler)},[]);
 useEffect(()=>{rail.current?.scrollTo({left:0,behavior:'instant'})},[filter]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape')setMenu(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
 const choose=f=>{setFilter(f);document.getElementById('cases').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})};
 const submit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);setDraft(Object.fromEntries(data));setBrief(`Даниил, здравствуйте! Хочу обсудить проект.\n\nИмя: ${data.get('name')}\nКомпания: ${data.get('company')}\nЗадача: ${data.get('service')}\n${data.get('message')||''}`)};
 return <>
 <header className="header wrap" id="top"><a className="small-logo" href="#top" aria-label="Loops — в начало">loops</a><nav className={menu?'nav is-open':'nav'} aria-label="Основная навигация">{[['Кейсы','cases'],['Услуги','services'],['Процесс','process'],['Обо мне','about'],['Контакты','contact']].map(([t,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{t}</a>)}</nav><Button href="#contact" className="header-cta">Обсудить проект</Button><button className="menu-button icon-button" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={25}/>:<List size={25}/>}</button></header>
 <main>
 <section className="hero" id="hero" ref={hero}>
  <div className="hero-inner wrap"><div className="hero-eyebrow"><span>ДАНИИЛ ГАЗИЗОВ</span><span>ТАШКЕНТ · УЗБЕКИСТАН</span></div><div className="hero-name"><h1>loops</h1><div className="hero-descriptor">маркетинг<br/>с продолжением</div></div><img className="hero-drawing" src={A+'marker-loop.png'} alt=""/><img className="floating compass" src={A+'compass.png'} alt=""/><img className="floating sail" src={A+'ref-sail.png'} alt=""/><div className="hero-portrait"><img src={A+'daniil.jpg'} alt="Даниил Газизов"/><Note>на связи лично</Note></div><div className="hero-bottom"><div className="hero-services"><span>Лидогенерация</span><span>ИИ-квалификация</span><span>Отделы продаж и CRM</span><span>Сквозная аналитика</span><Button href="#contact">Обсудить проект</Button></div><div className="hero-statement"><p>Соединяем рекламу,<br/>людей и процессы.<br/><span>Чтобы были продажи.</span></p><Note>всё связано.</Note></div><a className="scroll-link" href="#cases" aria-label="Перейти к кейсам"><ArrowDown size={21}/></a></div></div>
 </section>
 <section className="client-strip wrap" aria-label="Проекты, с которыми работали"><span className="eyebrow">ОПЫТ В РАЗНЫХ НИШАХ</span><div className="client-logos">{[['tak','TAK'],['chery','Chery'],['nwl','NWL'],['basalt','Basalt'],['dco','DCO'],['qwatt','Q.watt']].map(([f,n])=><img key={f} src={A+'clients/'+f+'.png'} alt={n}/>)}</div></section>
 <section className="cases-section section" id="cases"><Reveal className="wrap section-intro"><div><span className="eyebrow">НАШ ОПЫТ</span><h2>Разный бизнес.<br/>Один подход — <em>результат.</em></h2><p className="intro-copy">От стоматологии до производства. Погружаемся в специфику бизнеса и находим работающие решения.</p></div><Note className="cases-note">Цифры — из проектов.<br/>За каждой — своя история.<img src={A+'marker-loop.png'} alt=""/></Note></Reveal><div className="wrap"><div className="filters" role="group" aria-label="Направления бизнеса">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'active':''} aria-pressed={filter===f}>{f}</button>)}</div><div className="rail-heading"><h3>Избранные кейсы</h3><div className="rail-controls"><button className="icon-button" onClick={()=>rail.current.scrollBy({left:-680,behavior:scrollBehavior()})} disabled={!caseArrows.prev} aria-label="Предыдущие кейсы"><ArrowLeft/></button><button className="icon-button" onClick={()=>rail.current.scrollBy({left:680,behavior:scrollBehavior()})} disabled={!caseArrows.next} aria-label="Следующие кейсы"><ArrowRight/></button></div></div></div>
 <div className="case-rail" ref={rail} tabIndex="0" aria-label="Кейсы — прокручивайте горизонтально">{filtered.length?filtered.map(c=><button className="case-card" key={c.id} onClick={()=>setModal(c)} aria-label={`Открыть кейс ${c.name}`} style={{backgroundColor:c.color}}><img src={A+c.image} alt="" loading="lazy"/><div className="case-shade"/><div className="case-top"><h3>{c.name}</h3><span>{c.category}</span></div><div className="case-bottom"><strong>{c.result}</strong><span>{c.unit}</span><strong className="secondary-metric">{c.extra}</strong><span>{c.extraLabel}</span></div><span className="case-open"><ArrowUpRight size={22}/></span></button>):<div className="case-empty"><h3>В этой нише тоже есть опыт.</h3><p>Проекты — в списке ниже. Расскажу о подходе и подходящих примерах лично.</p><Button href="#contact">Обсудить задачу</Button></div>}</div><div className="wrap rail-caption"><span>Результаты конкретных проектов. Подробности и условия — внутри кейсов.</span><a href="https://loops.uz/cases.html" target="_blank" rel="noreferrer">Все кейсы <ArrowUpRight size={16}/></a></div>
 <Reveal className="wrap projects"><div className="rail-heading"><h3>Все направления</h3><Note>Найдите свой бизнес</Note></div><div className="sector-grid">{sectors.map((s,i)=><article className={`sector ${expanded===i?'expanded':''}`} key={s.name}><button className="sector-toggle" aria-expanded={expanded===i} onClick={()=>setExpanded(expanded===i?null:i)}><h4>{s.name}<span>{s.projects.length}</span></h4>{expanded===i?<Minus size={16}/>:<ArrowUpRight size={16}/>}</button><ul>{s.projects.slice(0,expanded===i?99:4).map(([n,d,l])=><li key={n}>{l&&l!=='viamed'?<img src={A+'clients/'+l+'.png'} alt="" loading="lazy"/>:null}<span><b>{n}</b><small>{d}</small></span></li>)}</ul>{expanded===i&&<button className="sector-action" onClick={()=>choose(s.filter)}>Посмотреть направление <ArrowRight size={15}/></button>}</article>)}</div><div className="project-invite"><Note>здесь может быть<br/>ваш следующий результат</Note><p>Обсудим, что можно сделать<br/>именно в вашем бизнесе.</p><Button href="#contact">Обсудить проект</Button></div></Reveal>
 </section>
 <section className="services-section section wrap" id="services"><Reveal className="section-intro"><div><span className="eyebrow">ЧЕМ МОГУ ПОМОЧЬ</span><h2>Соберём систему.<br/><em>Под вашу задачу.</em></h2></div><Note>от первого касания<br/>до сделки</Note></Reveal><div className="service-list">{[
 ['01','Лидогенерация','Meta Ads, B2B и маркетинг для клиник. Находим аудиторию, проверяем креативы, считаем качество обращений.','Трафик → целевой запрос','https://loops.uz/target/'],
 ['02','ИИ и автоматизация','Квалификация обращений, ответы на повторяющиеся вопросы и передача менеджеру с контекстом.','Запрос → понятная задача','https://loops.uz/ai-bot/'],
 ['03','Отдел продаж и CRM','Процесс обработки лидов, ответственность, обучение команды и контроль следующих шагов.','Задача → сделка','https://loops.uz/consulting/'],
 ['04','Сквозная аналитика','Собираем рекламу и продажи в одну картину: видно, какие действия приносят результат.','Данные → решения','https://adstat.uz']
 ].map(([n,t,d,l,url])=><Reveal key={n}><a className="service-row" href={url} target="_blank" rel="noreferrer"><span className="service-number">{n}</span><h3>{t}</h3><div><p>{d}</p><span className="service-tag">{l}</span></div><ArrowUpRight className="service-arrow" size={32}/></a></Reveal>)}</div></section>
 <section className="process-section section" id="process"><div className="wrap"><Reveal className="process-heading"><span className="eyebrow">КАК МЫ РАБОТАЕМ</span><h2>Без чёрного ящика.</h2><Note>Понятно, что делаем.<br/>Видно, что получается.</Note></Reveal><div className="process-grid"><div className="process-art"><img className="process-photo" src={A+'daniil.jpg'} alt="Даниил Газизов" loading="lazy"/><img className="process-loop" src={A+'marker-loop.png'} alt=""/><Note>Сначала разбираемся.<br/>Потом запускаем.</Note><div className="process-sticky-label">Смотрим<br/>на бизнес<br/><em>целиком.</em></div></div><div className="timeline">{[
 ['Знакомимся с задачей','Разбираемся в продукте, аудитории и целях. Определяем, что будет результатом именно для вас.'],
 ['Находим узкое место','Смотрим рекламу, посадочную страницу, CRM и обработку лидов. Не всегда проблема в количестве заявок.'],
 ['Собираем план','Выбираем инструменты, фиксируем этапы, ответственность и показатели. Готовим материалы и связки.'],
 ['Запускаем и проверяем','Выводим первую версию в работу, проверяем путь обращения и получаем реальные данные.'],
 ['Улучшаем по результатам','Проверяем гипотезы и качество лидов. Обсуждаем с продажами, что происходит после рекламы.'],
 ['Работаем в партнёрстве','Регулярно сверяем цифры и следующие шаги. Вы понимаете, что сделано и куда движется проект.']
 ].map(([t,d],i)=><Reveal className="timeline-step" key={t}><span className="step-number">{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></Reveal>)}</div></div></div></section>
 <section className="about-section section wrap" id="about"><span className="eyebrow">ЗА LOOPS СТОЯТ ЛЮДИ</span><Reveal className="about-display"><h2>На связи.<br/><em>Даниил.</em></h2><div className="about-portrait"><img src={A+'daniil.jpg'} alt="Даниил Газизов, основатель Loops" loading="lazy"/><Note>да, тот самый<br/>из кейсов</Note></div></Reveal><div className="about-copy"><p className="about-lead">Соединяю маркетинг,<br/>технологии и продажи.</p><div><p>Я Даниил Газизов. Работаю с лидогенерацией, выстраиваю отделы продаж и внедряю автоматизацию. Loops — место, где эти задачи складываются в одну систему.</p><p>Для каждого проекта собираем нужные компетенции. Начинаем с вашей задачи, а не с продажи заранее выбранного инструмента.</p><a className="text-link" href="https://loops.uz/about/" target="_blank" rel="noreferrer">Больше обо мне <ArrowUpRight size={18}/></a></div></div></section>
 <section className="contact-section section" id="contact"><div className="wrap contact-grid"><div className="contact-heading"><span className="eyebrow">ЕСТЬ ЗАДАЧА?</span><h2>Давайте<br/><em>обсудим.</em></h2><p>Расскажите про бизнес и то,<br/>что хочется изменить.</p><Note>без презентации<br/>на 100 слайдов :)</Note><a className="direct-contact" href={TG} target="_blank" rel="noreferrer"><PaperPlaneTilt size={21}/> Написать сразу в Telegram <ArrowUpRight size={18}/></a></div><div>{brief?<div className="brief-ready" role="status"><Check size={40}/><h3>Бриф готов.</h3><p>Осталось отправить его Даниилу в Telegram — и продолжим разговор.</p><pre>{brief}</pre><Button href={`${TG}?text=${encodeURIComponent(brief)}`} className="button-yellow" target="_blank" rel="noreferrer">Открыть Telegram</Button><button className="edit-brief" onClick={()=>setBrief(null)}>Изменить бриф</button></div>:<form className="contact-form" onSubmit={submit}><div className="form-row"><label>Как вас зовут<input name="name" defaultValue={draft.name||''} autoComplete="given-name" placeholder="Имя" required maxLength={80}/></label><label>Ваш бизнес<input name="company" defaultValue={draft.company||''} autoComplete="organization" placeholder="Компания или ниша" required maxLength={120}/></label></div><label>С чем нужна помощь<select name="service" defaultValue={draft.service||"Хочу разобраться с задачей"}><option>Хочу разобраться с задачей</option><option>Лидогенерация и реклама</option><option>ИИ и автоматизация</option><option>Отдел продаж и CRM</option><option>Сквозная аналитика</option></select></label><label>Пара слов о задаче<textarea name="message" defaultValue={draft.message||''} rows="4" placeholder="Что сейчас происходит и какой результат нужен?" maxLength={2000}/></label><p className="form-helper">Подготовим короткий бриф. Вы отправите его лично в Telegram.</p><Button className="button-yellow" type="submit">Подготовить бриф</Button></form>}</div></div></section>
 <section className="faq-section section wrap"><Reveal className="section-intro"><div><span className="eyebrow">ПЕРЕД СТАРТОМ</span><h2>Хорошие вопросы.</h2></div><Note>и прямые ответы</Note></Reveal><div className="faq-list">{[
 ['С какими проектами вы работаете?','С B2B-компаниями, производителями, клиниками и сервисным бизнесом. Важнее ниши — понятный продукт, возможность обрабатывать обращения и готовность работать с данными.'],
 ['Можно прийти только с одной задачей?','Да. Можно начать с рекламы, квалификации обращений, CRM или аналитики. Сначала разберёмся, как эта задача связана с остальным процессом.'],
 ['Сколько стоит работа?','Стоимость зависит от объёма, инструментов и участия вашей команды. На первом разговоре определим задачу, а затем подготовим конкретное предложение. Рекламный бюджет и сторонние сервисы обсуждаются отдельно.'],
 ['Вы гарантируете такие же цифры, как в кейсах?','Кейсы показывают опыт, а не универсальное обещание. На результат влияют продукт, спрос, бюджет, сезонность и работа продаж. До старта согласуем показатели и способ их оценки.']
 ].map(([q,a],i)=><div className="faq-item" key={q}><h3><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={`faq-${i}`}>{q}{faq===i?<Minus size={22}/>:<Plus size={22}/>}</button></h3><div id={`faq-${i}`} className={`faq-answer ${faq===i?'open':''}`} inert={faq!==i?true:undefined}><div><p>{a}</p></div></div></div>)}</div></section>
 <section className="articles-section section wrap" id="articles"><div className="rail-heading"><h2>По делу.</h2><div className="rail-controls"><button className="icon-button" onClick={()=>articleRail.current.scrollBy({left:-400,behavior:scrollBehavior()})} disabled={!articleArrows.prev} aria-label="Предыдущие материалы"><ArrowLeft/></button><button className="icon-button" onClick={()=>articleRail.current.scrollBy({left:400,behavior:scrollBehavior()})} disabled={!articleArrows.next} aria-label="Следующие материалы"><ArrowRight/></button></div></div><div className="article-rail" ref={articleRail}>{[
 ['01','КЛИНИКИ','Лиды ≠ пациенты.','Почему количество заявок ещё ничего не говорит об окупаемости рекламы.','leady-ne-pacienty','Качество важнее количества.'],['02','ЭКОНОМИКА','Сколько стоит пациент?','Как смотреть на расходы, визиты и результат конкретной клиники.','stoimost-pacienta-tashkent','Считаем до конца.'],['03','ПРОЦЕССЫ','Почему не возвращаются?','Что происходит после первого визита и как работать с обратной связью.','pochemu-pacienty-ne-vozvrashayutsya','После рекламы тоже есть жизнь.']
 ].map(([n,c,t,d,slug,note])=><a href={`https://loops.uz/articles/${slug}/`} target="_blank" rel="noreferrer" key={slug} className="article-card"><div className="article-art"><span>{n}</span><Note>{note}</Note><img src={A+'marker-loop.png'} alt=""/></div><div className="article-body"><span className="eyebrow">{c}</span><h3>{t}</h3><p>{d}</p><span className="text-link">Читать материал <ArrowUpRight size={18}/></span></div></a>)}</div></section>
 </main>
 <footer className="footer"><div className="wrap footer-top"><div><span className="eyebrow">СЛЕДУЮЩАЯ ИСТОРИЯ — ВАША</span><h2>Начнём с разговора.</h2></div><Button href={TG} className="button-yellow" target="_blank" rel="noreferrer">Написать Даниилу</Button></div><div className="wrap footer-links"><span>© 2026 Loops · Даниил Газизов</span><span>Ташкент · работаем онлайн</span><a href="https://t.me/daniil_loops" target="_blank" rel="noreferrer">Telegram-канал <ArrowUpRight size={15}/></a><a href="#top">Наверх <ArrowUpRight size={15}/></a></div><div className="footer-word" aria-hidden="true">loops</div></footer>
 {modal&&<Modal data={modal} onClose={()=>setModal(null)}/>}
 </>;
}
