import React,{useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,List,X} from '@phosphor-icons/react';
import {services} from './services';
import {cases} from './data';
import {CasePreview} from './CasePreview';
const A='/leadgeneration/assets/';
function LinkButton({href,children,light=false}){return <a className={`button ${light?'button-yellow':''}`} href={href}>{children}<ArrowUpRight size={19}/></a>}
export function ServicePage({slug}){
 const s=services[slug];const [menu,setMenu]=useState(false),[preview,setPreview]=useState(null);
 useEffect(()=>{const key=e=>{if(e.key==='Escape')setMenu(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
 const proof=s.caseIds.map(id=>cases.find(c=>c.id===id)).filter(Boolean);
 return <div className={'service-page service-page--'+slug}>
 <a className="skip-link" href="#content">Перейти к содержанию</a>
 <header className="header wrap"><a className="small-logo" href="/" aria-label="Loops — на главную">loops</a><nav className={menu?'nav is-open':'nav'} aria-label="Основная навигация"><a href="/#services">Услуги</a><a href="#work" onClick={()=>setMenu(false)}>Подход</a><a href={proof.length?'#proof':'/#cases'} onClick={()=>setMenu(false)}>Кейсы</a><a href="#faq" onClick={()=>setMenu(false)}>Вопросы</a></nav><LinkButton href="#contact">Обсудить проект</LinkButton><button className="menu-button icon-button" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={25}/>:<List size={25}/>}</button></header>
 <main id="content">
 <section className="service-hero wrap"><nav className="service-breadcrumb" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/#services">Услуги</a><span>/</span><span>{s.name}</span></nav>
 <div className="service-hero-grid"><div><span className="eyebrow">{s.number} / {s.name} · LOOPS</span><h1>{s.heading}<br/><em className="service-underline">{s.accent}</em></h1><p className="service-intro">{s.intro}</p><div className="service-hero-actions"><LinkButton href="#contact">Обсудить задачу</LinkButton><a href="#work" className="text-link">Как работаем <ArrowRight size={17}/></a></div></div>
 <figure className={'service-visual service-visual--'+s.visual}><figcaption className="eyebrow">{s.label}</figcaption><ol>{s.stages.map(([title,text],i)=><li key={title}><span className="visual-index">0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div>{i<3&&<span className="visual-connector" aria-hidden="true">↓</span>}</li>)}</ol><span className="hand-note">{s.note.split('\n').map((line,i)=><React.Fragment key={i}>{line}<br/></React.Fragment>)}</span></figure></div>
 <div className="service-facts"><span>Даниил Газизов · на связи лично</span><span>Ташкент · работаем онлайн</span><span>Реклама → люди → процессы</span></div></section>
 <section className="wrap service-section"><div className="service-section-head"><span className="eyebrow">УЗНАЁТЕ СВОЮ СИТУАЦИЮ?</span><h2>Начинаем с того,<br/><em>что мешает расти.</em></h2></div><div className="service-pains">{s.pains.map(([title,text],i)=><article key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="service-work-band" id="work"><div className="wrap service-work-grid"><div className="service-section-head"><span className="eyebrow">ЧТО БУДЕМ ДЕЛАТЬ</span><h2>Разберём.<br/>Соберём.<br/><em className="service-underline">Доведём.</em></h2><p>У каждого этапа есть задача и результат, который можно обсудить с командой.</p></div><ol className="service-steps">{s.work.map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section className="wrap service-section service-outcomes"><div className="service-section-head"><span className="eyebrow">ЧТО ОСТАЁТСЯ У ВАС</span><h2>Рабочая система.<br/><em>Понятная команде.</em></h2></div><ul>{s.outcomes.map((x,i)=><li key={x}><span aria-hidden="true">↗</span>{x}</li>)}</ul></section>
 {proof.length>0&&<section className="wrap service-section" id="proof"><div className="service-section-head service-proof-head"><div><span className="eyebrow">ИЗ НАШЕГО ОПЫТА</span><h2>{s.caseHeading}</h2></div><a className="text-link" href="/#projects">Все проекты <ArrowUpRight/></a></div><div className="service-proof-grid">{proof.map(c=><a key={c.id} className="service-proof" href={`/cases/case-${c.id}/`} aria-haspopup="dialog" aria-label={`Открыть кейс ${c.name}`} onClick={e=>{if(!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey&&e.button===0){e.preventDefault();setPreview(c);window.loopsTrack?.('case_preview_open',c.id)}}}><div className="service-proof-photo" style={{'--cover-image':`url("${A+c.image}")`}}><img src={A+c.image} alt={c.name} loading="lazy" width="640" height="800"/></div><div className="service-proof-copy"><span className="eyebrow">{c.category}</span><h3>{c.name}<ArrowUpRight size={24}/></h3><strong>{c.result}</strong><p>{c.unit}</p><span className="text-link">Посмотреть историю <ArrowRight/></span></div></a>)}</div><p className="service-fine">Результаты отдельных проектов. Условия и контекст — в полном кейсе.</p></section>}
 {s.plans.length>0&&<section className="wrap service-section" id="pricing"><div className="service-section-head"><span className="eyebrow">ФОРМАТ РАБОТЫ</span><h2>Под вашу задачу.<br/><em>С понятным объёмом.</em></h2></div><div className="service-plans">{s.plans.map(([title,price,text])=><article key={title}><h3>{title}</h3><strong>{price}</strong><p>{text}</p><a className="text-link" href="#contact">Обсудить формат <ArrowUpRight/></a></article>)}</div><p className="service-fine">Итоговый состав работ, сроки и стоимость фиксируем в предложении. Рекламный бюджет и платные сторонние сервисы — отдельно.</p></section>}
 {slug==='analytics'&&<section className="wrap analytics-product"><div><span className="eyebrow">ИНСТРУМЕНТЫ ВНУТРИ ПРОЦЕССА</span><h2>Adstat.<br/><em>Данные для решений.</em></h2><p>Используем инструменты, которые подходят вашим источникам и задачам. Сначала определяем вопросы бизнеса, затем — отчёты и интеграции.</p></div><LinkButton href="https://adstat.uz">Познакомиться с Adstat</LinkButton></section>}
 <section className="wrap service-section service-faq" id="faq"><div className="service-section-head"><span className="eyebrow">ПЕРЕД СТАРТОМ</span><h2>Хорошие<br/><em>вопросы.</em></h2></div><div>{s.faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="service-contact" id="contact"><div className="wrap"><span className="eyebrow">ДАВАЙТЕ ОБСУДИМ</span><div className="service-contact-grid"><h2>{s.cta.split('\n').map((line,i)=><React.Fragment key={line}>{i>0&&<br/>}{line}</React.Fragment>)}</h2><div><p>{s.ctaText}</p><LinkButton href={'https://t.me/dani_gzv?text='+encodeURIComponent('Даниил, здравствуйте! Хочу обсудить: '+s.name+'.')} light>Написать Даниилу</LinkButton><a className="service-contact-person" href="/#about"><img src={A+'daniil-avatar-2026.webp'} width="56" height="56" alt="Даниил Газизов"/><span>На связи лично.<br/><small>Даниил Газизов · Loops</small></span></a></div></div></div></section>
 <section className="wrap service-section service-siblings"><span className="eyebrow">ВСЁ СВЯЗАНО</span><h2>Следующий шаг<br/><em>в вашей системе.</em></h2><nav aria-label="Другие услуги">{Object.entries(services).filter(([key])=>key!==slug).map(([key,x])=><a href={'/'+key+'/'} key={key}><span>{x.number}</span>{x.name}<ArrowUpRight size={24}/></a>)}</nav></section>
 </main><footer className="wrap service-footer"><a className="small-logo" href="/">loops</a><span>© 2026 Loops · Ташкент</span><a href="/#projects">Кейсы ↗</a><a href="https://t.me/dani_gzv">Telegram ↗</a></footer>
 {preview&&<CasePreview data={preview} onClose={()=>setPreview(null)}/>}
 </div>
}
