#!/usr/bin/env python3
"""
Loops — case generator. SINGLE SOURCE OF TRUTH = cases/cases.json (+ cases/_bodies/<id>.html).
Run:  python3 scripts/build-cases.py
Generates:
  - cases-data.js              (card data + renderer; powers homepage preview, /cases.html, "Другие кейсы")
  - cases/case-<id>/index.html (one detail page per case)
Add/edit a case = edit cases/cases.json + cases/_bodies/<id>.html, then run this script.
Everything (homepage, cases list, detail page, cross-links) updates from the one registry.
"""
import json, os, re, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CASES = json.load(open(os.path.join(ROOT, "cases/cases.json"), encoding="utf-8"))

def plain(s):
    return html.unescape(re.sub("<[^>]+>", "", s)).replace("\xa0", " ").strip()

# ---------- cases-data.js (cards) ----------
ICON = {
 "box":'<svg viewBox="0 0 24 24" aria-hidden="true"><path pathLength="1" d="M3 7.5 12 3l9 4.5-9 4.5z"/><path pathLength="1" d="M3 7.5V16l9 4.5 9-4.5V7.5"/><path pathLength="1" d="M12 12v8.5"/></svg>',
 "car":'<svg viewBox="0 0 24 24" aria-hidden="true"><path pathLength="1" d="M3.5 13l2-5.5h13l2 5.5"/><path pathLength="1" d="M3 13h18v4.5H3z"/><path pathLength="1" d="M6.5 17.5v1.5M17.5 17.5v1.5"/></svg>',
 "heart":'<svg viewBox="0 0 24 24" aria-hidden="true"><path pathLength="1" d="M12 20S4.5 15.5 4.5 10.2A3.7 3.7 0 0 1 12 7.3a3.7 3.7 0 0 1 7.5 2.9C19.5 15.5 12 20 12 20Z"/></svg>',
 "factory":'<svg viewBox="0 0 24 24" aria-hidden="true"><path pathLength="1" d="M3 21V10l5.5 3.5V10l5.5 3.5V6.5L20.5 9.5V21z"/><path pathLength="1" d="M3 21h18"/></svg>',
 "truck":'<svg viewBox="0 0 24 24" aria-hidden="true"><path pathLength="1" d="M2.5 6.5h11.5v9.5H2.5z"/><path pathLength="1" d="M14 9.5h4l3.5 3.5V16H14z"/><path pathLength="1" d="M6.5 16.5v1.5M17 16.5v1.5"/></svg>',
}

def js_str(s): return json.dumps(s, ensure_ascii=False)

def build_cards_js():
    items = []
    for c in CASES:
        tags = ", ".join(js_str(t) for t in c.get("tags", []))
        items.append(
            "    {\n"
            f"      id: {js_str(c['id'])},\n"
            f"      img: {js_str(c['img'])},\n"
            f"      client: {js_str(c['client'])},\n"
            f"      cat: {js_str(c['cat'])},\n"
            f"      niche: ICON.{c.get('niche','box')},\n"
            f"      metric: {js_str(c['metric'])},\n"
            f"      unit: {js_str(c['unit'])},\n"
            f"      tags: [{tags}],\n"
            f"      note: {js_str(c.get('note',''))}\n"
            "    }"
        )
    nl = "\n"
    icon_js = ("," + nl).join(f"    {k}:{nl}      {js_str(v)}" for k, v in ICON.items())
    items_str = ("," + nl).join(items)
    return f"""/* ===========================================================
   Loops — case cards data + renderer.
   GENERATED by scripts/build-cases.py from cases/cases.json — do not edit by hand.
   =========================================================== */
(function () {{
  var ICON = {{
{icon_js}
  }};

  window.LOOPS_CASES = [
{items_str}
  ];

  var ARROW =
    '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">' +
    '<path d="M5 12h14M13 6l6 6-6 6" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round"/></svg>';

  window.caseCardHTML = function (c, opts) {{
    opts = opts || {{}};
    var href = (opts.href || "/cases/case-{{id}}/").replace("{{id}}", c.id);
    var goLabel = opts.goLabel || "Смотреть кейс";
    var tags = (c.tags || [])
      .map(function (t) {{ return '<span class="case-tag">' + t + "</span>"; }})
      .join("");
    var note = c.note ? '<p class="case-note">' + c.note + "</p>" : "";
    return (
      '<div class="card hoverable case-card reveal" id="case-' + c.id + '">' +
        '<div class="case-photo">' +
          '<img class="case-img" src="images/' + c.img + '" alt="' + c.client + '" loading="lazy" />' +
          '<span class="case-niche">' + (c.niche || "") + c.cat + "</span>" +
        "</div>" +
        '<div class="case-body">' +
          '<span class="case-client">' + c.client + "</span>" +
          '<div class="case-metric"><span class="case-num">' + c.metric +
            '<span class="unit">' + c.unit + "</span></span></div>" +
          '<div class="case-tags">' + tags + "</div>" +
          note +
          '<a class="case-go" href="' + href + '">' + goLabel + ARROW + "</a>" +
        "</div>" +
      "</div>"
    );
  }};

  window.renderCases = function (container, opts) {{
    if (!container) return;
    opts = opts || {{}};
    var list = window.LOOPS_CASES;
    if (opts.limit) list = list.slice(0, opts.limit);
    container.innerHTML = list
      .map(function (c) {{ return window.caseCardHTML(c, opts); }})
      .join("");
  }};
}})();
"""

# ---------- detail page ----------
def kpis_html(c):
    return "\n".join(
        f'          <div class="case-kpi"><b>{k["v"]}</b><span>{k["l"]}</span></div>'
        for k in c["kpis"])

def metabar_html(c):
    rows = "\n".join(
        f'          <div class="m"><div class="m-l">{m["l"]}</div><div class="m-v">{m["v"]}</div></div>'
        for m in c["metabar"])
    logo = f'\n          <img class="m-logo" src="{c["logo"]}" alt="{c["client"]}" />' if c.get("logo") else ""
    return rows + logo

def ogtitle(c): return c["title"].replace(" | Loops", "")

def build_page(c):
    cid = c["id"]
    url = f"https://loops.uz/cases/case-{cid}/"
    body = open(os.path.join(ROOT, f"cases/_bodies/{cid}.html"), encoding="utf-8").read().strip()
    headline = plain(c["h1"])
    jsonld = {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "Article", "headline": headline,
             "author": {"@type": "Person", "name": "Даниил Газизов", "url": "https://loops.uz/about/"},
             "publisher": {"@type": "Organization", "name": "Loops", "url": "https://loops.uz/"},
             "image": c["ogimage"], "mainEntityOfPage": url, "description": plain(c["desc"])},
            {"@type": "BreadcrumbList", "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Главная", "item": "https://loops.uz/"},
                {"@type": "ListItem", "position": 2, "name": "Кейсы", "item": "https://loops.uz/cases.html"},
                {"@type": "ListItem", "position": 3, "name": c["crumb"], "item": url}]},
        ]}
    ld = json.dumps(jsonld, ensure_ascii=False, indent=2)
    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{c['title']}</title>
<link rel="icon" type="image/png" href="/images/favicon.png" />
<meta name="description" content="{c['desc']}" />
<link rel="canonical" href="{url}" />
<meta name="robots" content="index,follow" />
<meta property="og:type" content="article" />
<meta property="og:site_name" content="Loops" />
<meta property="og:url" content="{url}" />
<meta property="og:title" content="{ogtitle(c)}" />
<meta property="og:description" content="{c['desc']}" />
<meta property="og:image" content="{c['ogimage']}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{ogtitle(c)}" />
<meta name="twitter:description" content="{c['desc']}" />
<meta name="twitter:image" content="{c['ogimage']}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="/styles.css" />
<script type="application/ld+json">
{ld}
</script>
<script>
  try {{
    if (window.matchMedia("(prefers-reduced-motion: no-preference)").matches
        && "IntersectionObserver" in window) {{
      document.documentElement.classList.add("anim");
    }}
  }} catch (e) {{}}
</script>
<script defer data-website-id="dfid_f3VYRJCEILPpM9zBm2vdN" data-domain="loops.uz" src="https://datafa.st/js/script.js"></script>
</head>
<body>

<header id="site-header">
  <div class="wrap nav">
    <a href="/" class="logo" aria-label="Loops — на главную">
      <img class="logo-img" src="/images/loops-logo.png" alt="Loops" />
    </a>
    <nav class="nav-links" aria-label="Основная навигация">
      <a href="/#directions">Чем занимаюсь</a>
      <a href="/cases.html" aria-current="page">Кейсы</a>
      <a href="/clinics/">Клиники</a>
      <a href="/about/">Обо мне</a>
      <a href="/#contact">Контакты</a>
    </nav>
    <a href="/#contact" class="btn btn-ghost header-cta">Оставить заявку</a>
  </div>
</header>

<main id="top">

  <section class="hero" aria-label="Кейс {c['client']}">
    <div class="wrap">
      <div class="card hero-text reveal" style="min-height:auto;">
        <div class="crumbs">
          <a href="/">Главная</a><span class="sep">›</span>
          <a href="/cases.html">Кейсы</a><span class="sep">›</span>
          <span class="cur">{c['crumb']}</span>
        </div>
        <h1 style="font-size:clamp(36px,5vw,64px);">{c['h1']}</h1>
        <p class="lead">{c['lead']}</p>

        <div class="case-kpis">
{kpis_html(c)}
        </div>

        <div class="case-meta">
{metabar_html(c)}
        </div>
      </div>
    </div>
  </section>

  <section class="sec-pad" style="padding-top:0;">
    <div class="wrap">
      <article class="case-prose">
{body}
      </article>
    </div>
  </section>

  <section class="sec-pad" style="padding-top:0;">
    <div class="wrap">
      <h2 class="sec-title" style="margin-bottom:28px;">Другие кейсы</h2>
      <div class="cases-grid" id="otherCases"></div>
    </div>
  </section>

</main>

<footer>
  <div class="wrap">
    <div class="foot-grid">
      <div class="foot-about">
        <a href="/" class="logo"><img class="logo-img" src="/images/loops-logo.png" alt="Loops" /></a>
        <p>Личный бренд Даниила. Лидогенерация с&nbsp;ИИ-ассистентом, отделы продаж и&nbsp;собственные продукты — всё, что нужно, чтобы реклама превращалась в&nbsp;деньги.</p>
      </div>
      <div class="foot-cols">
        <div class="foot-col">
          <h4>Навигация</h4>
          <a href="/#directions">Чем занимаюсь</a>
          <a href="/cases.html">Кейсы</a>
          <a href="/clinics/">Клиники</a>
          <a href="/consulting/">Консалтинг</a>
          <a href="/about/">Обо мне</a>
        </div>
        <div class="foot-col">
          <h4>Связь</h4>
          <a href="https://t.me/dani_gzv" target="_blank" rel="noopener">Telegram</a>
          <a href="https://instagram.com/danii_gzv" target="_blank" rel="noopener">Instagram</a>
          <a href="tel:+998900012373">+998 90 001 23 73</a>
        </div>
      </div>
    </div>
    <div class="foot-bottom">
      <span>© 2026 Loops · Даниил</span>
      <span>Ташкент</span>
    </div>
  </div>
</footer>

<script src="/cases-data.js"></script>
<script>
  (function () {{
    var grid = document.getElementById("otherCases");
    if (!grid || !window.LOOPS_CASES || !window.caseCardHTML) return;
    var others = window.LOOPS_CASES.filter(function (c) {{ return c.id !== "{cid}"; }}).slice(0, 3);
    grid.innerHTML = others.map(function (c) {{
      return window.caseCardHTML(c, {{ href: "/cases/case-{{id}}/", goLabel: "Смотреть кейс" }});
    }}).join("");
  }})();
</script>
<script src="/site.js"></script>

</body>
</html>
"""

def main():
    open(os.path.join(ROOT, "cases-data.js"), "w", encoding="utf-8").write(build_cards_js())
    for c in CASES:
        d = os.path.join(ROOT, f"cases/case-{c['id']}")
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "index.html"), "w", encoding="utf-8").write(build_page(c))
    print(f"Built cases-data.js + {len(CASES)} detail pages:", ", ".join(c["id"] for c in CASES))

if __name__ == "__main__":
    main()
