#!/usr/bin/env python3
"""Shared static editorial pages. Sources: content/articles.json, cases/_content.
No analytics or internal case source data is duplicated into public JSON.
"""
from pathlib import Path
import json,html,re,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1];BASE='https://loops.uz';DATE='2026-09-27'
e=lambda x:html.escape(str(x),quote=True)
articles=json.loads((R/'content/articles.json').read_text()); registry=json.loads((R/'cases/cases.json').read_text())
cases=[json.loads((R/'cases/_content'/f'{c["id"]}.json').read_text()) for c in registry]
industries=json.loads((R/'_handoff/leadgeneration-source/src/industries.json').read_text())
analytics=(R/'_handoff/leadgeneration-source/src/analytics.html').read_text()
links={'target':'Лидогенерация','ai-bot':'ИИ и автоматизация','consulting':'Продажи и CRM','analytics':'Сквозная аналитика',**{k:v['name'] for k,v in industries.items()}}
def shell(path,title,desc,body,kind='WebPage',extra=None):
 url=BASE+path;graph=[{'@type':kind,'@id':url+'#page','url':url,'name':title,'headline':title,'description':desc,'inLanguage':'ru','dateModified':DATE,'author':{'@type':'Person','@id':BASE+'/#daniil','name':'Даниил Газизов','url':BASE+'/about/'},'publisher':{'@type':'Organization','@id':BASE+'/#organization','name':'Loops','url':BASE+'/'},'mainEntityOfPage':url},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Loops','item':BASE+'/'},{'@type':'ListItem','position':2,'name':title,'item':url}]}]
 if extra: graph+=extra
 return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} — Loops</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{url}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="{'article' if kind=='Article' else 'website'}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}/leadgeneration/assets/daniil-avatar-2026.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/leadgeneration/assets/favicon.png"><link rel="stylesheet" href="/leadgeneration/assets/fonts.css"><link rel="stylesheet" href="/cases/format-v2.css"><link rel="stylesheet" href="/editorial.css"><script src="/editorial.js" defer></script><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('<',chr(92)+'u003c')}</script></head><body><a class="skip-link" href="#content">Перейти к содержанию</a><header class="wrap case-header"><a class="wordmark" href="/" aria-label="Loops — на главную">loops</a><nav aria-label="Основная навигация"><a href="/#industries">Направления</a><a href="/cases.html">Кейсы</a><a href="/articles/">Материалы</a></nav><a class="button" href="https://t.me/dani_gzv">Обсудить проект ↗</a></header><main id="content">{body}</main><footer class="wrap editorial-footer"><a class="wordmark" href="/">loops</a><p>Даниил Газизов · Ташкент, Узбекистан</p><nav aria-label="Контакты и информация"><a href="/about/">О Данииле</a><a href="https://t.me/dani_gzv">Написать лично ↗</a><a href="https://t.me/daniil_loops">Telegram-канал ↗</a><a href="/privacy/">Данные и обратная связь</a></nav></footer>{analytics}</body></html>'''
def save(path,text):
 p=R/path.lstrip('/');p=p/'index.html' if not p.suffix else p;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
def cta(title='Есть похожая задача?',text='Расскажите о бизнесе и о том, что хотите улучшить. Обсудим следующий шаг лично.'):
 return f'<section class="wrap editorial-cta"><span class="eyebrow">НА СВЯЗИ ЛИЧНО</span><h2>{title}</h2><p>{text}</p><a class="button button-yellow" href="https://t.me/dani_gzv">Написать Даниилу ↗</a><a class="text-link" href="/#contact">Или подготовить короткий бриф →</a></section>'
def cards(items):
 return '<div class="reading-grid">'+''.join(f'<a href="/articles/{x["slug"]}/"><span class="eyebrow">{e(x["category"])}</span><h2>{e(x["title"])}</h2><p>{e(x["summary"])}</p><span class="text-link">Читать материал ↗</span></a>' for x in items)+'</div>'
for a in articles:
 title=a['title']; body=f'<section class="wrap editorial-hero"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/articles/">Материалы</a></nav><span class="eyebrow">{e(a["category"])}</span><h1>{e(title)}</h1><p class="editorial-lead">{e(a["summary"])}</p><div class="byline"><img src="/leadgeneration/assets/daniil-avatar-2026.webp" width="48" height="48" alt=""><div><a href="/about/">Даниил Газизов</a><span>Обновлено 27 сентября 2026</span></div></div></section>'
 toc=''.join(f'<a href="#section-{i}">{e(s["title"])}</a>' for i,s in enumerate(a['sections'],1))
 body+=f'<div class="wrap editorial-layout"><aside><nav aria-label="Содержание статьи"><span class="eyebrow">В МАТЕРИАЛЕ</span>{toc}</nav></aside><article class="editorial-prose">'
 for i,s in enumerate(a['sections'],1):body+=f'<section id="section-{i}"><h2>{e(s["title"])}</h2>'+''.join(f'<p>{e(p)}</p>' for p in s['paragraphs'])+'</section>'
 if a['sources']:body+='<section><h2>Официальные источники</h2><ul>'+''.join(f'<li><a href="{e(x["url"])}" rel="noopener">{e(x["title"])} ↗</a></li>' for x in a['sources'])+'</ul><p>Сведения об инструменте сверены при обновлении материала. Доступность и условия могут меняться.</p></section>'
 c=next(x for x in cases if x['id']==a['case']);body+=f'<div class="reading-next"><span class="eyebrow">ОТ МАТЕРИАЛА К ПРАКТИКЕ</span><a href="/{a["service"]}/">{e(links[a["service"]])} ↗</a><a href="/cases/case-{c["id"]}/">Кейс {e(c["client"])}: {e(c["headline"])} ↗</a></div></article></div>'+cta()
 save('/articles/'+a['slug']+'/',shell('/articles/'+a['slug']+'/',title,a['summary'],body,'Article'))
body='<section class="wrap editorial-hero"><span class="eyebrow">ПРАКТИКА LOOPS</span><h1>Разобраться.<br><em>И сделать лучше.</em></h1><p class="editorial-lead">Материалы о рекламе, квалификации заявок и продажах. С понятными определениями, примерами и следующими шагами.</p></section><section class="wrap editorial-list">'+cards(articles[:7])+'</section><section class="wrap editorial-list"><h2 class="list-heading">Инструменты и развитие команды.</h2>'+cards(articles[7:])+'</section>'+cta()
save('/articles/',shell('/articles/','Материалы о маркетинге, B2B-лидогенерации и аналитике','Практические материалы Loops: квалификация заявок, стоимость лида, CRM, маркетинг клиник и применение ИИ.',body,'CollectionPage'))
# Static searchable case catalog; ordinary click opens a dialog before the full story.
body='<section class="wrap editorial-hero"><span class="eyebrow">24 ИСТОРИИ ИЗ ПРАКТИКИ</span><h1>Разный бизнес.<br><em>Конкретная работа.</em></h1><p class="editorial-lead">Посмотрите задачи, решения и результаты. Нажмите на проект: сначала краткий обзор, затем полный кейс.</p><label class="catalog-search">Найти проект или направление<input id="case-search" type="search" placeholder="Например, клиника или B2B" autocomplete="off"></label><p id="case-count" aria-live="polite">24 кейса</p></section><section class="wrap catalog-grid" aria-label="Все кейсы">'
for c in cases:
 metrics=' · '.join(m['value']+' '+m['label'] for m in c['metrics']);body+=f'''<a class="catalog-card" href="/cases/case-{c['id']}/" data-case="{c['id']}" data-summary="{e(c['summary'])}" aria-haspopup="dialog"><div class="catalog-media" style="--cover-image:url('{e(c['cover'])}')"><img src="{e(c['cover'])}" width="640" height="800" alt="{e(c['coverAlt'])}" loading="lazy"></div><div class="catalog-copy"><span class="eyebrow">{e(c['industry'])}</span><h2>{e(c['client'])}</h2><p>{e(c['headline'])}</p><span class="catalog-metric">{e(metrics)}</span><span class="text-link">Краткий обзор ↗</span></div></a>'''
body+='</section><p class="wrap catalog-empty" hidden>Не нашли такой проект. Попробуйте другое название или <a href="https://t.me/dani_gzv">расскажите о задаче Даниилу</a>.</p><p class="wrap editorial-note">Результаты относятся к отдельным проектам и описанным условиям. Показатели разных этапов — диалоги, лиды, визиты и сделки — не взаимозаменяемы.</p>'+cta()+'<dialog id="case-preview" aria-labelledby="preview-title"><button class="dialog-close" aria-label="Закрыть предпросмотр">×</button><div class="dialog-layout"><div class="catalog-media"><img id="preview-cover" alt="" width="640" height="800"></div><div class="dialog-copy"><span class="eyebrow">ИСТОРИЯ ПРОЕКТА</span><h2 id="preview-title"></h2><p id="preview-summary"></p><p id="preview-metrics"></p><a class="button button-yellow" id="preview-full" href="/cases.html">Смотреть полный кейс ↗</a></div></div></dialog>'
save('/cases.html',shell('/cases.html','Кейсы Loops — реклама, квалификация заявок и продажи','24 кейса Loops: B2B, клиники, производство, автобизнес, рестораны и фитнес. Задачи, подход, результаты и примеры работы.',body,'CollectionPage'))
body='''<section class="wrap editorial-hero about-grid"><div><span class="eyebrow">ОСНОВАТЕЛЬ LOOPS</span><h1>На связи.<br><em>Даниил Газизов.</em></h1><p class="editorial-lead">Соединяю маркетинг, технологии и продажи. Работаю в Ташкенте, с бизнесом в Узбекистане и на других рынках.</p><a class="button" href="https://t.me/dani_gzv">Обсудить задачу лично ↗</a></div><img class="about-photo" src="/leadgeneration/assets/daniil-avatar-2026.webp" width="640" height="640" alt="Даниил Газизов — основатель Loops"></section><div class="wrap editorial-layout"><aside><span class="eyebrow">ЧЕМ МОГУ ПОМОЧЬ</span></aside><article class="editorial-prose"><section><h2>Смотрю на путь обращения целиком.</h2><p>Реклама, первый диалог, квалификация, CRM и работа менеджера связаны. Поэтому начинаем с задачи бизнеса и ищем этап, который мешает получить результат.</p><p>В Loops собираем нужные компетенции под проект. Состав работ, ответственность и показатели обсуждаем до запуска, чтобы команда понимала следующий шаг.</p></section><section><h2>Опыт, который можно изучить.</h2><p>На сайте опубликованы проекты из медицины, логистики, опта, производства, автобизнеса, ресторанов и других сфер. В каждом кейсе — задача, действия и результат в контексте конкретного бизнеса.</p><p><a href="/cases.html">Посмотреть все 24 кейса →</a></p></section><section><h2>Как начинается работа.</h2><p>Вы рассказываете о продукте, географии и текущей ситуации. Мы обсуждаем ограничения, данные и возможный подход. Затем фиксируем состав работ, этапы, бюджет и способ оценки.</p><p>Цифры другого проекта помогают оценить опыт, но не заменяют разбор вашей задачи. Для стоимости лида, сделки и возврата затрат нужны собственные исходные данные.</p></section><section><h2>Личный блог.</h2><div class="reading-next"><a href="https://t.me/daniil_loops">Telegram ↗</a><a href="https://instagram.com/danii_gzv">Instagram ↗</a><a href="https://www.youtube.com/@dani_gzv">YouTube ↗</a><a href="https://www.threads.net/@danii_gzv">Threads ↗</a></div></section></article></div>'''+cta()
save('/about/',shell('/about/','Даниил Газизов — маркетолог и основатель Loops','Даниил Газизов, Ташкент: лидогенерация, ИИ-квалификация, продажи и CRM. Подход к работе, опубликованные кейсы и личные контакты.',body,'ProfilePage',[{'@type':'Person','@id':BASE+'/#daniil','name':'Даниил Газизов','url':BASE+'/about/','jobTitle':'Маркетолог, основатель Loops','sameAs':['https://t.me/dani_gzv','https://instagram.com/danii_gzv','https://www.youtube.com/@dani_gzv','https://www.threads.net/@danii_gzv']}]))
body='''<section class="wrap editorial-hero"><span class="eyebrow">ДАННЫЕ И ОБРАТНАЯ СВЯЗЬ</span><h1>Понятно, что<br><em>происходит с данными.</em></h1><p class="editorial-lead">Как устроены бриф, переход в Telegram и аналитика на сайте Loops.</p></section><article class="wrap editorial-prose narrow"><section><h2>Бриф на главной</h2><p>Форма собирает черновик сообщения в вашем браузере. Нажатие «Подготовить бриф» само по себе не отправляет заявку команде. Вы можете проверить текст и отправить его лично в Telegram.</p></section><section><h2>Связь с Даниилом</h2><p>Ссылки на Telegram открывают внешний сервис. Дальнейшая переписка происходит в нём. Передавайте только данные, необходимые для обсуждения задачи; закрытые клиентские сведения для первого контакта не нужны.</p></section><section><h2>Аналитика</h2><p>На сайте используются Яндекс Метрика и DataFast для анализа посещений и взаимодействий. Метрика включает Вебвизор. Поля брифа помечены для скрытия содержимого в Вебвизоре; в собственные события Loops не передаёт текст брифа, телефон или email.</p><p>У аналитических сервисов есть собственные условия обработки данных: <a href="https://yandex.ru/legal/confidential/">Яндекс</a> и <a href="https://datafa.st/privacy-policy">DataFast</a>. Блокировщики и настройки браузера могут ограничивать сбор статистики.</p></section><section><h2>Вопросы по данным</h2><p>По вопросам об информации, переданной в переписке с Loops, напишите <a href="https://t.me/dani_gzv">Даниилу в Telegram</a>. Эта страница объясняет фактическую работу сайта и не заменяет договорённости по конкретному проекту.</p></section></article>'''
save('/privacy/',shell('/privacy/','Данные и обратная связь','Как работают бриф, Telegram и аналитика сайта Loops. Контакт по вопросам о данных.',body))
# Preserve existing URL set, add only genuinely created pages, set real modification dates.
root=ET.parse(R/'sitemap.xml').getroot();ns='{http://www.sitemaps.org/schemas/sitemap/0.9}'
urls={u.find(ns+'loc').text for u in root};urls.update(BASE+'/'+x+'/' for x in industries);urls.update(BASE+'/articles/'+a['slug']+'/' for a in articles);urls.add(BASE+'/privacy/')
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{e(u)}</loc><lastmod>{DATE}</lastmod></url>\n' for u in sorted(urls))+'</urlset>\n')
llms='# Loops — Даниил Газизов\n\n> Реклама, квалификация обращений, продажи и CRM. Ташкент, Узбекистан. Публичные результаты описаны в контексте отдельных проектов; кейсы не являются прогнозом для другого бизнеса.\n\n## Услуги и направления\n'
llms+=''.join(f'- [{e(n)}]({BASE}/{k}/): подход, состав работ и кейсы.\n' for k,n in links.items())
llms+='\n## Кейсы\n'+''.join(f'- [{c["client"]}]({BASE}/cases/case-{c["id"]}/): {c["headline"]}.\n' for c in cases)
llms+='\n## Практические материалы\n'+''.join(f'- [{a["title"]}]({BASE}/articles/{a["slug"]}/): {a["summary"]}\n' for a in articles)
llms+='\n## Автор и контакт\n- [Даниил Газизов](https://loops.uz/about/): подход к работе и публичные профили.\n- [Обсудить проект](https://t.me/dani_gzv): личный контакт в Telegram.\n'
(R/'llms.txt').write_text(llms)
print(f'Built 11 articles, catalog, about, privacy; sitemap {len(urls)} URLs')

# Helpful error page uses the same design, retains a real HTTP 404 from nginx.
error_body='<section class="wrap editorial-hero"><span class="eyebrow">404 / СТРАНИЦА НЕ НАЙДЕНА</span><h1>Продолжим<br><em>с нужного места.</em></h1><p class="editorial-lead">Возможно, ссылка устарела. На главной собраны услуги и направления, а в каталоге — все опубликованные кейсы.</p><a class="button button-yellow" href="/">На главную ↗</a><a class="text-link" href="/cases.html">Посмотреть кейсы →</a></section>'
save('/404.html',shell('/404.html','Страница не найдена','Найдите нужное направление или кейс Loops.',error_body).replace('index,follow,max-image-preview:large','noindex,follow'))
